name: Unit Tests
on:
  push:
    branches:
      - main
      - "release/**"
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '**.go'
      - go.mod
      - '.github/workflows/**'

jobs:
  unit-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Setup cookies
        run: |
          cat /etc/issue
          bash scripts/gogetcookie.sh
      - name: Running unit tests
        run: make test


