name: Docs and Website Lint
on:
  push:
    branches:
      - main
      - "release/**"
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - .github/workflows/website-lint.yaml
      - docs/**

jobs:
  website-generation:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Get dependencies
        run: go mod download
      - name: Generate the website
        run: make website-generation
      - name: git diff
        run: |
          git diff --compact-summary --exit-code || \
            (echo; echo "Unexpected difference in directories after code generation. Run 'make website-generation' command and commit."; exit 1)
  website-lint-spellcheck-tffmt:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: 'go.mod'
          cache: true
      - run: docker version
      - name: Setup tools
        run: make setup
      - name: Lint website
        run: make website-lint
  markdown-lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: avto-dev/markdown-lint@v1
        with:
          args: 'docs'
          config: '.markdownlint.yml'

